CONTIKI_PROJECT = udp-blackhole-client udp-blackhole-server
all: $(CONTIKI_PROJECT)

CONTIKI=../..

# ----- Descomente as linhas abaixo para inserir análise de energia dos nós ----- 
# include $(CONTIKI)/Makefile.dir-variables
# MODULES += $(CONTIKI_NG_SERVICES_DIR)/simple-energest 

include $(CONTIKI)/Makefile.include
